server:
  port: 8081
  servlet:
    context-path: /sims

spring:
  datasource:
    data-username: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/Demo?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456

mybatis:
  # 配置映射类所在包名
  type-aliases-package: com.freeyun.simsplus.dao.domain
  # 配置mapper xml文件所在路径，这里是一个数组
  mapper-locations:
      - mappers/StudentMapper.xml


